services:
  tenzir-node:
    build:
      context: .
      args:
        - TENZIR_VERSION=main
    environment:
      - TENZIR_ENDPOINT=tenzir-node:5158
      - TENZIR_TOKEN=${TENZIR_TOKEN:-}
      - TENZIR_PLATFORM_CONTROL_ENDPOINT=${TENZIR_PLATFORM_CONTROL_ENDPOINT:-}
    entrypoint:
      - tenzir-node
    volumes:
      - tenzir-lib:/var/lib/tenzir/
      - tenzir-log:/var/log/tenzir/
    healthcheck:
      test: tenzir --connection-timeout=30s --connection-retry-delay=1s 'api /ping'
      interval: 30s
      retries: 1

  tenzir:
    build:
      context: .
      args:
        - TENZIR_VERSION=main
    profiles:
      - donotstart
    depends_on:
      - tenzir-node
    environment:
      - TENZIR_ENDPOINT=tenzir-node:5158

  tests:
    build:
      context: .
      target: test
      args:
        - TENZIR_VERSION=main
    profiles:
      - donotstart
    volumes:
      - ./bats/data/reference/:/tmp/example/bats/data/reference/

volumes:
  tenzir-lib:
    driver: local
  tenzir-log:
    driver: local
