services:
  tenzir-node:
    build:
      context: .
      args:
        - TENZIR_VERSION=main
    environment:
      - TENZIR_ALLOW_UNSAFE_PIPELINES=true
      - TENZIR_ENDPOINT=tenzir-node:5158
      - TENZIR_PLUGINS__PLATFORM__API_KEY=${TENZIR_PLUGINS__PLATFORM__API_KEY:-}
      - TENZIR_PLUGINS__PLATFORM__CONTROL_ENDPOINT=${TENZIR_PLUGINS__PLATFORM__CONTROL_ENDPOINT:-wss://ws.tenzir.app/production}
      - TENZIR_PLUGINS__PLATFORM__TENANT_ID=${TENZIR_PLUGINS__PLATFORM__TENANT_ID:-}
    ports:
      - 5158:5158
    entrypoint:
      - tenzir-node
    volumes:
      - tenzir-node:/var/lib/tenzir/
      - tenzir-node:/var/log/tenzir/
      - tenzir-node:/var/cache/tenzir/
    healthcheck:
      test: tenzir --connection-timeout=30s --connection-retry-delay=1s 'api /ping'
      interval: 30s
      retries: 1

  tenzir:
    build:
      context: .
      args:
        - TENZIR_VERSION=main
    profiles:
      - donotstart
    depends_on:
      - tenzir-node
    environment:
      - TENZIR_ALLOW_UNSAFE_PIPELINES=true
      - TENZIR_ENDPOINT=tenzir-node:5158
    volumes:
      - tenzir-node:/var/cache/tenzir/

  tests:
    build:
      context: .
      target: example-test
      args:
        - TENZIR_VERSION=main
    profiles:
      - donotstart
    volumes:
      - ./example/integration/data/reference/:/plugins/example/integration/data/reference/

volumes:
  tenzir-node:
    driver: local
