name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
  merge_group:
    types:
      - checks_requested

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}

jobs:
  tests:
    name: Tests (${{ matrix.version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          # We always test against the the current development version and the
          # latest stable release.
          - main
          - latest
          # If you'd like to test with further Tenzir versions or rely on a
          # specific Tenzir version in your deployment, you can also test
          # against it by specifying the version number explicitly:
          # - v4.14.0
          # - v4.13.1
          # - v4.12.2
          # - v4.11.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          docker compose build --build-arg TENZIR_VERSION=${{ matrix.version }}
      - name: Test
        run: |
          docker compose run --build tests
          git diff --exit-code
