name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
  merge_group:
    types:
      - checks_requested

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}

jobs:
  tests:
    name: Tests (${{ matrix.version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - main
          - latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          docker compose build --build-arg TENZIR_VERSION=${{ matrix.version }}
      - name: Test
        run: |
          docker compose run --build tests
          git diff --exit-code
